# Generated by Django 3.2.8 on 2026-09-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('funcionario', 'Funcionario'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
