# Generated by Django 3.2.8 on 2026-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipos_tramite',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='tramites.TipoTramite', verbose_name='Tipos de trámite que resuelve'),
        ),
    ]
