# Generated by Django 3.2.8 on 2026-09-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_estimada_resolucion',
            field=models.DateField(blank=True, help_text='Fecha estimada por el ciudadano para la resolución', null=True),
        ),
    ]
